### list developers
GET http://localhost:3000/developers

### get developer
GET http://localhost:3000/developers/dev_VYZvx5-ht-Q0x9n4abhn2

### create developer
POST http://localhost:3000/developers
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@acme.com",
    "dateOfBirth": "1990-01-01"
}

### update developer
PATCH http://localhost:3000/developers/dev_DR4OEE2RADSsoU5p5ckK0
Content-Type: application/json

{
    "email": "teste@acme.com"
}

### delete developer
DELETE http://localhost:3000/developers/dev_VYZvx5-ht-Q0x9n4abhn2